IF NOT EXISTS (SELECT * FROM sys.types st JOIN sys.schemas ss ON st.schema_id = ss.schema_id WHERE st.name = N'ScheduleDetails' AND ss.name = N'rpt')
CREATE TYPE [RPT].[ScheduleDetails] AS TABLE(
	[ID] [bigint] NOT NULL,
	[ScheduleCode] [nvarchar](100) NULL,
	[ScheduleName] [nvarchar](100) NULL,
	[ScheduleuserID] [bigint] NULL,
	[StartDateTime] [datetime] NULL,
	[EndDateTime] [datetime] NULL,
	[AsessmentCode] [nvarchar](100) NULL,
	[AssesmentName] [nvarchar](200) NULL,
	[AssessmentInstruction] [nvarchar](1000) NULL,
	[ExamMaximumMarks] [int] NULL,
	[OrgazationCode] [nvarchar](100) NULL,
	[UserCode] [nvarchar](200) NULL,
	[LoginName] [nvarchar](200) NULL,
	[FirstName] [nvarchar](200) NULL,
	[LastName] [nvarchar](200) NULL,
	[ProfilePhotoPath] [nvarchar](max) NULL,
	[ProctoringType] [int] NULL,
	[IsLiveModeRequired] [bit] NULL,
	[IsImageModeRequired] [bit] NULL,
	[IsReviewerModeRequired] [bit] NULL,
	[IsPhotoComparionRequired_Student] [bit] NULL,
	[IsPhotoComparionRequired_Proctor] [bit] NULL,
	[PhotoComparisonType] [int] NULL,
	[IsCandidateRoomVideoRequired] [bit] NULL,
	[IsSecureBrowserExam] [bit] NULL,
	[SecureBrowserExamType] [int] NULL,
	[IsSecondaryCameraRequired] [bit] NULL,
	[IsAudioAnalysisRequired] [bit] NULL,
	[IsChatFeatureRequired_Live] [bit] NULL,
	[IsSecondaryCameraAnalysisRequired_Live] [bit] NULL,
	[IsScreenRecordingRequired_Live] [bit] NULL,
	[RecordingType_Live] [int] NULL,
	[IsSecondaryCameraAnalysisRequired_RecordReview] [bit] NULL,
	[IsScreenRecordingRequired_RecordReview] [bit] NULL,
	[RecordingType_RecordReview] [int] NULL,
	[PhotoCaptureInterval_ImageMode] [int] NULL,
	[IsImageModeAnalysisRequired] [int] NULL,
	[IsFMMCountRequired] [bit] NULL,
	[IsHMMCountRequired] [bit] NULL,
	[IscorrectFlag] [bit] NULL,
	[Createdby] [bigint] NULL
)
GO


